import Head from 'next/head';
import { links } from '@/assest/data/profile';

// Person schema. Highest-leverage SEO item on the site: `sameAs` tells Google that
// this domain, the LinkedIn profile, the Medium profile, the X account, and GitHub
// are ONE entity. Without it they compete as separate weak results for "Mann Gupta";
// with it they consolidate. `jobTitle` + `knowsAbout` are what let the entity rank
// for role queries rather than just for the name.
const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Mann Gupta',
  jobTitle: 'AI Product Manager',
  email: `mailto:${links.email}`,
  url: 'https://gmannn.netlify.app/',
  sameAs: [links.linkedin, links.github, links.medium, links.x],
  knowsAbout: [
    'AI Product Management',
    'Product Management',
    'LLM Agents',
    'Retrieval Augmented Generation',
    'AI Unit Economics',
    'Pricing and Packaging',
    'Product Strategy',
    'Market Entry Strategy',
    'Market Sizing',
    'Management Consulting',
    'Market Microstructure',
    'Go-to-Market Strategy',
  ],
  alumniOf: {
    '@type': 'CollegeOrUniversity',
    name: 'Rajiv Gandhi Institute of Petroleum Technology (RGIPT)',
  },
  worksFor: {
    '@type': 'Organization',
    name: 'Acceltancy',
  },
};

const SITE_ORIGIN = "https://gmannn.netlify.app";

// 1200x630 share card, generated by scripts/generate-og.js from scripts/og-card.html.
const DEFAULT_OG_IMAGE = "/og-image.png";

const SEO = ({
  title = "Mann Gupta | AI Product Manager",
  description = "AI Product Manager who owns products end to end: discovery, pricing, unit economics, and shipped software.",
  image = DEFAULT_OG_IMAGE,
  url = "https://gmannn.netlify.app/",
  includePersonSchema = false,
  keywords,
  noindex = false,
}) => {
  // og:image and twitter:image MUST be absolute. LinkedIn, Slack, WhatsApp, and X
  // all fetch the image from a server that has no idea what the relative path is
  // relative TO, so a bare "/og-image.png" silently yields a preview with no image.
  const absoluteImage = image?.startsWith("http")
    ? image
    : `${SITE_ORIGIN}${image?.startsWith("/") ? "" : "/"}${image || DEFAULT_OG_IMAGE}`;

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      {keywords && <meta name="keywords" content={keywords} />}
      <link rel="canonical" href={url} />
      <meta
        name="robots"
        content={noindex ? "noindex, follow" : "index, follow, max-image-preview:large"}
      />
      <meta name="author" content="Mann Gupta" />

      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="Mann Gupta" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={absoluteImage} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:alt" content="Mann Gupta, AI Product Manager" />
      <meta property="og:url" content={url} />

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={absoluteImage} />
      <meta name="twitter:creator" content="@_guptamann_" />

      {includePersonSchema && (
        <script
          type="application/ld+json"
          // Static object built at module scope from our own data, no user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }}
        />
      )}
    </Head>
  );
};

export default SEO;
